# Generated by Django 5.2.7 on 2025-10-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchrequest',
            unique_together=set(),
        ),
    ]