# Generated by Django 5.2.7 on 2025-10-23 06:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('number_of_courts', models.PositiveIntegerField(default=1, help_text='Number of courts available')),
                ('has_lights', models.BooleanField(default=False, help_text='Night play available')),
                ('has_backboard', models.BooleanField(default=False, help_text='Practice wall available')),
                ('court_surface', models.CharField(choices=[('HARD', 'Hard Court'), ('CLAY', 'Clay Court'), ('GRASS', 'Grass Court'), ('SYNTHETIC', 'Synthetic')], default='HARD', max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('owner_contact', models.CharField(blank=True, help_text='Phone/WhatsApp number', max_length=50)),
                ('owner_bank_account', models.CharField(blank=True, help_text='Bank name and account number', max_length=100)),
                ('owner_qris_image', models.ImageField(blank=True, help_text='QRIS payment code', null=True, upload_to='qris/')),
                ('opening_time', models.TimeField(default=datetime.time(6, 0))),
                ('closing_time', models.TimeField(default=datetime.time(22, 0))),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='["parking", "locker", "shower", "cafe"]')),
                ('court_image', models.ImageField(blank=True, null=True, upload_to='courts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('booker_name', models.CharField(help_text='Full name for reservation', max_length=100)),
                ('booker_phone', models.CharField(help_text='Contact number', max_length=20)),
                ('booker_email', models.EmailField(blank=True, max_length=254)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Awaiting Payment Confirmation'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING_PAYMENT', max_length=20)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('notes', models.TextField(blank=True, help_text='Special requests or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.playingfield')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='playingfield',
            index=models.Index(fields=['city', 'is_active'], name='booking_pla_city_0588eb_idx'),
        ),
        migrations.AddIndex(
            model_name='playingfield',
            index=models.Index(fields=['price_per_hour'], name='booking_pla_price_p_ed0737_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='booking_boo_user_id_dddf68_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['field', 'booking_date', 'start_time'], name='booking_boo_field_i_a708d0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'booking_date'], name='booking_boo_status_816464_idx'),
        ),
    ]
