# Generated by Django 5.2.7 on 2025-10-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingfield',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL for court thumbnail'),
        ),
    ]
