# Generated by Django 5.2.7 on 2025-10-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_playingfield_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playingfield',
            name='owner_qris_image',
        ),
    ]
