# Generated by Django 5.2.7 on 2025-10-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Player', max_length=200)),
                ('lokasi', models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], max_length=50)),
                ('harga', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
