# Generated by Django 5.2.7 on 2025-10-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_lapangan_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lapangan',
        ),
    ]
