# Generated by Django 5.2.7 on 2025-10-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lapangan', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('komentar', models.TextField()),
            ],
        ),
    ]
