# Generated by Django 5.2.7 on 2025-10-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_playingfield_image_url'),
        ('review', '0004_alter_review_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='lapangan',
        ),
        migrations.AddField(
            model_name='review',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.playingfield'),
        ),
    ]
