# Generated by Django 5.2.7 on 2025-10-17 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PLAYER', 'Player'), ('ADMIN', 'Admin')], default='PLAYER', max_length=50)),
                ('lokasi', models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.CharField(choices=[('static/image/avatar1.svg', 'Avatar 1'), ('static/image/avatar2.svg', 'Avatar 2'), ('static/image/avatar3.svg', 'Avatar 3'), ('static/image/avatar4.svg', 'Avatar 4'), ('static/image/avatar5.svg', 'Avatar 5')], default='static/image/avatar1.svg', max_length=100)),
                ('jumlah_kemenangan', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
