# Generated by Django 5.2.7 on 2025-10-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('image/avatar1.svg', 'Avatar 1'), ('image/avatar2.svg', 'Avatar 2'), ('image/avatar3.svg', 'Avatar 3'), ('image/avatar4.svg', 'Avatar 4'), ('image/avatar5.svg', 'Avatar 5')], default='image/avatar1.svg', max_length=100),
        ),
    ]
