# Generated by Django 5.2.7 on 2025-10-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('image/avatar1.png', 'Avatar 1'), ('image/avatar2.png', 'Avatar 2'), ('image/avatar3.png', 'Avatar 3'), ('image/avatar4.png', 'Avatar 4'), ('image/avatar5.png', 'Avatar 5')], default='image/avatar1.png', max_length=100),
        ),
    ]
